[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.14.5"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-multierror"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/tj/go-progress"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
